5 features into two classes neural network


In [1]:
import torch
import torch.nn as nn

In [4]:
 # inherting from the nn.Module class
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()# invoking the constructor
    self.linear = nn.Linear(num_features,1) # one neuron
    self.sigmoid  = nn.Sigmoid() # sigmoid activation

  def forward(self,features):
    out = self.linear(features) # z = wx+b
    out = self.sigmoid(out)
    return out


In [3]:
features = torch.rand(10,5)

In [5]:
model = Model(features.shape[1])
model(features)

tensor([[0.6649],
        [0.6055],
        [0.6635],
        [0.6285],
        [0.6048],
        [0.6716],
        [0.6074],
        [0.6708],
        [0.6458],
        [0.6367]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear.weight

Parameter containing:
tensor([[ 0.0494, -0.0498, -0.1465,  0.2562,  0.0947]], requires_grad=True)

In [7]:
model.linear.bias

Parameter containing:
tensor([0.4440], requires_grad=True)

In [8]:
!pip install torchinfo

In [9]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Better neural network

In [12]:
# 5 features , 3 neurons(relu) , one output layer(sigmoid)

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid  = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out


In [13]:
model = Model(features.shape[1])
model(features)

tensor([[0.5907],
        [0.5794],
        [0.5983],
        [0.5875],
        [0.5985],
        [0.6104],
        [0.5933],
        [0.6160],
        [0.5856],
        [0.5741]], grad_fn=<SigmoidBackward0>)

In [15]:
model.linear1.weight

Parameter containing:
tensor([[ 0.1813, -0.1964,  0.2739, -0.0068,  0.4429],
        [-0.2302,  0.2391, -0.0793, -0.0268, -0.1754],
        [ 0.3477,  0.0187,  0.3120, -0.0694, -0.4149]], requires_grad=True)

In [16]:
model.linear2.weight

Parameter containing:
tensor([[ 0.3244,  0.0719, -0.0986]], requires_grad=True)

In [17]:
model.linear1.bias

Parameter containing:
tensor([-0.0577, -0.1821,  0.1283], requires_grad=True)

In [18]:
model.linear2.bias

Parameter containing:
tensor([0.3108], requires_grad=True)

In [19]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
#   def forward(self,features):
#   out = self.linear1(features)
#   out = self.relu(out)
#   out = self.linear2(out)
#   out = self.sigmoid(out)
#   return out

# This is very hectic so we can use the sequential class

In [21]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
          nn.Linear(num_features,3),
          nn.ReLU(),
          nn.Linear(3,1),
          nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

In [22]:
model = Model(features.shape[1])
model(features)

tensor([[0.4410],
        [0.4604],
        [0.4490],
        [0.4542],
        [0.4181],
        [0.4453],
        [0.4547],
        [0.4514],
        [0.4350],
        [0.4645]], grad_fn=<SigmoidBackward0>)

In [23]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00