In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [5]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [7]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [8]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim= 2))
model.add(Dense(1,activation='linear'))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.get_weights()

[array([[-0.8687464 , -0.63499504],
        [ 0.9086038 , -0.11859536]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.99980986],
        [0.4397056 ]], dtype=float32),
 array([0.], dtype=float32)]

In [13]:
optimizer= keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='mean_squared_error',optimizer=optimizer)
model.fit(X,y,epochs=75)

Epoch 1/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 702ms/step - loss: 7.1443
Epoch 2/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 5.8623
Epoch 3/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 4.8270
Epoch 4/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 4.0378
Epoch 5/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 3.4860
Epoch 6/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 3.1499
Epoch 7/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 2.9905
Epoch 8/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.9534
Epoch 9/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.9798
Epoch 10/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 3.0201
Epoch 11/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 3.0407
Epoch 12/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 3.0239
Epoch 13/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 2.9648
Epoch 14/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 2.8676
Epoch 15/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 2.7414
Epoch 16/75
1/1 ━━━━━━━━━━━━━━━

In [14]:
model.get_weights()

[array([[-0.4841287 , -0.31721553],
        [ 0.9870299 , -0.01796908]], dtype=float32),
 array([0.24519102, 0.21937326], dtype=float32),
 array([[0.79942876],
        [0.08891435]], dtype=float32),
 array([0.25990686], dtype=float32)]